version: "3.7"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "redisdata:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
volumes:
  redisdata:
    driver: local
