version: "3.7"

services:
  mysql:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secretpass}"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    volumes:
      - "mysqldata:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

volumes:
  mysqldata:
    driver: local
